### ISSUE TITLE
Transformer model to API takes too long to respond

### ISSUE THREAD

**Issue by AyeshaSarwar** [iamrajatroy/IN-translate-app#1]
I have
![code](https://user-images.githubusercontent.com/51691311/146529983-d34714c1-0332-4d37-9600-f077999077b2.PNG)
 finetuned a longformer encoder decoder model, and trying to convert it into an api but model takes too long to load that api throws a not responding error.

**Comment by iamrajatroy** [comment]
Please raise issues related to this repository/project only. 

For queries, please send a message in the help channel to my slack - https://join.slack.com/t/aiknowledgesharing/shared_invite/zt-pic27h2u-vL5qUKgJgX~530Z7rTBBNA

Thanks.
